# Generated by Django 6.0 on 2025-12-23 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_about'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'About'},
        ),
        migrations.AlterField(
            model_name='about',
            name='about_description',
            field=models.TextField(max_length=500),
        ),
    ]
