# Generated by Django 6.0 on 2025-12-23 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_alter_about_options_alter_about_about_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
